Add support for DeleteFactor and GetFactor methods
workos/workos-go pull request #172
Opened 2022-10-10 19:56 UTC by AshGodfrey

Add support for delete factor and get factor methods
Add tests for delete factor and get factor methods

2022-10-20 13:48 UTC, blairlunceford requested changes

2022-10-20 13:48 UTC, blairlunceford commented on pkg/mfa/client.go
> +	ID string
It looks like the convention is to have a more descriptive name - could we use `AuthenticationFactorID` instead for both of these new methods?

2022-10-20 13:48 UTC, blairlunceford commented on pkg/mfa/client.go
> +// DeleteFactor deletes a Factor.
nit: change comment to `Deletes an authentication factor` to be in line with other methods.

2022-10-20 13:48 UTC, blairlunceford commented on pkg/mfa/client.go
> +// GetFactor gets a Factor.
nit: change comment to `Retrieves an authentication factor` to be in line with other methods.

2022-10-24 16:14 UTC, AshGodfrey commented
Going to need to check why this failing.

2022-10-24 16:20 UTC, AshGodfrey commented
Also I switched the ID name as requested, but a lot of our other go functions do just use ID. Not sure if we want to keep it inline with other functions or go with the more descriptive name.

2022-10-24 21:59 UTC, blairlunceford commented
> Also I switched the ID name as requested, but a lot of our other go functions do just use ID. Not sure if we want to keep it inline with other functions or go with the more descriptive name.

Thanks! Yes, but this pattern will follow the `ChallengeOpts` and `VerifyOpts` structs in this file, so I think it's good to just make the change here.

2022-10-24 21:59 UTC, blairlunceford approved these changes

2022-10-25 16:25 UTC, merged